# A example config file
# mv config.toml.example config.toml
# cargo run . --bin rustpbx --conf config.toml

http_addr = "0.0.0.0:8080"
log_level = "debug"
#log_file = "/tmp/rustpbx.log"
stun_server = "stun.l.google.com:19302"
recorder_path = "/tmp/recorders"
media_cache_path = "/tmp/mediacache"

[ua]
addr="0.0.0.0"
udp_port=13050 # don't use 5060


[proxy]
modules = ["acl", "auth", "registrar", "call"]
addr = "0.0.0.0"
udp_port = 15060
registrar_expires = 60
ws_handler= "/ws"

# ACL rules
acl_rules = [
    "allow 10.0.0.0/8",
    "deny 0.123.4.0/16",
    "allow all",
    "deny all"
]

[ua.handler]
type = "webhook"
url = "http://localhost:8090/webhook"
method = "POST"


# MediaProxy configuration
[proxy.media_proxy]
mode = "auto"
rtp_start_port = 20000
rtp_end_port = 30000

# external_ip = "192.168.1.1"  # Set to your external IP
# force_proxy = ["192.168.1.100"]  # Optional: IP addresses to always proxy

[proxy.user_backend]
type = "memory"
users = [
    { username = "bob", password = "123456" },
    { username = "alice", password = "123456" },
]

[callrecord]
type = "local"
root = "/tmp/cdr"

[proxy.trunks.wuhoo]
dest = "sip:123.456.789.00:1234"

[[proxy.routes]]
name = "default"
priority = 1
dest = "wuhoo"

[proxy.routes.match]
"to.user" = "^\\+.*"

[proxy.routes.rewrite]
"to.user" = "+{1}"
"to.host" = "123.456.789.00:1234"
"from.user" = "12345"
"from.host" = "123.456.789.00:1234"

# Deepgram AI Configuration
[deepgram]
# API key for Deepgram services (can also be set via DEEPGRAM_API_KEY environment variable)
# api_key = "your_deepgram_api_key_here"

# ASR (Automatic Speech Recognition) Configuration
[deepgram.asr]
model = "nova"
language = "en"  # English language default
encoding = "linear16"
sample_rate = 16000
channels = 1
interim_results = true
punctuate = true
smart_format = true
endpointing = 1000
vad_events = true
# endpoint = "wss://api.deepgram.com/v1/listen"  # Optional custom endpoint

# TTS (Text-to-Speech) Configuration  
[deepgram.tts]
model = "aura-asteria-en"  # Deepgram Aura voice model
encoding = "linear16"  # Valid options: linear16, mp3, flac, opus, aac, mulaw, alaw
sample_rate = 16000
# endpoint = "https://api.deepgram.com/v1/speak"  # Optional custom endpoint

# Pipecat Media Server Configuration
[pipecat]
# Enable Pipecat integration (set to true to use external AI processing)
enabled = true
# Pipecat server WebSocket URL
server_url = "ws://localhost:8765/ws/rustpbx"
# Use Pipecat for AI processing instead of internal services
use_for_ai = true
# Fallback to internal AI processing if Pipecat is unavailable
fallback_to_internal = true
# Connection timeout in seconds
connection_timeout = 30
# Default system prompt for AI conversations
default_system_prompt = "You are a helpful AI assistant in a voice conversation. Respond naturally and conversationally. Keep responses brief but informative."
# Enable metrics collection
enable_metrics = true
# Enable debug logging for Pipecat communication
debug_logging = false

# Pipecat reconnection settings
[pipecat.reconnect]
enabled = true
max_attempts = 5
initial_delay = 1
max_delay = 30
backoff_multiplier = 2.0

# Pipecat audio processing settings
[pipecat.audio]
sample_rate = 16000
channels = 1
frame_size = 160  # 10ms at 16kHz
buffer_size = 10
enable_compression = false
encoding = "linear16"
