//! Classify a SIP [`TerminatedReason`] into the [`FailureSource`] recorded on
//! the CDR, so downstream consumers can attribute a failure (e.g. a 503) to our
//! own SBC versus the upstream carrier leg.

use crate::callrecord::FailureSource;
use rsipstack::dialog::dialog::TerminatedReason;

/// Map a terminated reason to the originating side, or `None` for a clean
/// (non-failure) teardown.
pub(crate) fn classify_failure_source(reason: &TerminatedReason) -> Option<FailureSource> {
    match reason {
        // Generated by our own SBC/proxy.
        TerminatedReason::ProxyError(_) | TerminatedReason::ProxyAuthRequired => {
            Some(FailureSource::Sbc)
        }
        // Returned by the upstream/callee leg (the carrier trunk on outbound),
        // or the callee never answered in time.
        TerminatedReason::UasOther(_)
        | TerminatedReason::UasBusy
        | TerminatedReason::UasDecline
        | TerminatedReason::Timeout => Some(FailureSource::Upstream),
        // Originated on the calling (UAC) leg.
        TerminatedReason::UacOther(_) | TerminatedReason::UacBusy => Some(FailureSource::Caller),
        // Clean teardown / caller abandonment — not a failure to attribute.
        TerminatedReason::UacBye | TerminatedReason::UasBye | TerminatedReason::UacCancel => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rsipstack::sip::StatusCode;

    #[test]
    fn proxy_error_is_sbc() {
        assert_eq!(
            classify_failure_source(&TerminatedReason::ProxyError(
                StatusCode::ServiceUnavailable
            )),
            Some(FailureSource::Sbc)
        );
    }

    #[test]
    fn proxy_auth_required_is_sbc() {
        assert_eq!(
            classify_failure_source(&TerminatedReason::ProxyAuthRequired),
            Some(FailureSource::Sbc)
        );
    }

    #[test]
    fn uas_other_is_upstream() {
        // The carrier trunk relayed a non-2xx (e.g. a 503) — "Vodafone's side".
        assert_eq!(
            classify_failure_source(&TerminatedReason::UasOther(
                StatusCode::ServiceUnavailable
            )),
            Some(FailureSource::Upstream)
        );
    }

    #[test]
    fn uas_busy_is_upstream() {
        assert_eq!(
            classify_failure_source(&TerminatedReason::UasBusy),
            Some(FailureSource::Upstream)
        );
    }

    #[test]
    fn uas_decline_is_upstream() {
        assert_eq!(
            classify_failure_source(&TerminatedReason::UasDecline),
            Some(FailureSource::Upstream)
        );
    }

    #[test]
    fn timeout_is_upstream() {
        // No final response from the called side within the timer.
        assert_eq!(
            classify_failure_source(&TerminatedReason::Timeout),
            Some(FailureSource::Upstream)
        );
    }

    #[test]
    fn uac_other_is_caller() {
        assert_eq!(
            classify_failure_source(&TerminatedReason::UacOther(
                StatusCode::ServiceUnavailable
            )),
            Some(FailureSource::Caller)
        );
    }

    #[test]
    fn uac_busy_is_caller() {
        assert_eq!(
            classify_failure_source(&TerminatedReason::UacBusy),
            Some(FailureSource::Caller)
        );
    }

    #[test]
    fn clean_uac_bye_is_not_a_failure() {
        assert_eq!(classify_failure_source(&TerminatedReason::UacBye), None);
    }

    #[test]
    fn clean_uas_bye_is_not_a_failure() {
        assert_eq!(classify_failure_source(&TerminatedReason::UasBye), None);
    }

    #[test]
    fn uac_cancel_is_not_a_failure() {
        // Caller abandoned before completion — nothing to attribute.
        assert_eq!(classify_failure_source(&TerminatedReason::UacCancel), None);
    }
}
