//! 503-attribution — add `failure_source` to `rustpbx_call_records`.
//!
//! Records which side a call failure originated on ("sbc" | "upstream" |
//! "caller"), so a SIP 503 generated by our own SBC can be distinguished from
//! one relayed by the upstream carrier leg. Nullable (NULL for a successful or
//! clean-hangup call), persisted by `persist_call_record` and read back by
//! `From<Model>`. Additive, idempotent (`has_column` guard), no-op `down` per
//! the codebase convention.

use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let table_name = "rustpbx_call_records";

        if !manager.has_column(table_name, "failure_source").await? {
            manager
                .alter_table(
                    Table::alter()
                        .table(crate::models::call_record::Entity)
                        .add_column(
                            ColumnDef::new(crate::models::call_record::Column::FailureSource)
                                .string()
                                .null(),
                        )
                        .to_owned(),
                )
                .await?;
        }

        Ok(())
    }

    async fn down(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
        // No-op down, matching the other add_*_column migrations (additive,
        // never reversed).
        Ok(())
    }
}
